const express=require('express');
const router=express.Router();
const ctrl=require('../controllers/pedidos.controller');
const {verificarToken,apenasAdmin}=require('../middlewares/auth.middleware');
router.use(verificarToken);
router.get('/meus',         ctrl.meusPedidos);
router.post('/',            ctrl.criar);
router.get('/historico',    apenasAdmin, ctrl.historico);
router.get('/',             apenasAdmin, ctrl.listarTodos);
router.get('/:id',          apenasAdmin, ctrl.detalhe);
router.put('/:id/status',   apenasAdmin, ctrl.atualizarStatus);
router.put('/:id/cancelar', apenasAdmin, ctrl.cancelar);
module.exports=router;
